#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade HG on Sat Oct 19 14:23:25 2013

import wx

# begin wxGlade: extracode
# end wxGlade



class BcliFileBrowser(wx.Frame):
	def __init__(self, parent, name, field, ref):
		# begin wxGlade: BcliFileBrowser.__init__
		#kwds["style"] = wx.DEFAULT_FRAME_STYLE
		wx.Frame.__init__(self, parent)
		self.Bind(wx.EVT_CLOSE, self.OnClose)
		
		self.prnt = parent
		self.name = name
		self.name.Enable(False)
		self.field = field
		
		self.ref = ref
		title = ""
		if self.ref == 0:
			title = "BcliFileBrowser ~ sélection de l'exécutable"
		elif self.ref == 1:
			title = "BcliFileBrowser ~ sélection de la source"
		elif self.ref == 2:
			title = "BcliFileBrowser ~ sélection de la destination"
			
		self.title = title
		
		#self.prnt.button_1.Enable(False)
		
		self.path = ""
		
		self.text_ctrl_1 = None
		if self.ref == 0:
			self.text_ctrl_1 = wx.GenericDirCtrl(self, -1, size=(500,300), style=0)
		elif self.ref == 1:
			self.text_ctrl_1 = wx.GenericDirCtrl(self, -1, size=(500,300), style=wx.DIRCTRL_SHOW_FILTERS,filter="Blend files (*.blend)|*.blend")
		elif self.ref == 2:
			self.text_ctrl_1 = wx.GenericDirCtrl(self, -1, size=(500,300), style=wx.DIRCTRL_DIR_ONLY)
			
		self.static_line_1 = wx.StaticLine(self, -1)
		self.button_1 = wx.Button(self, -1, "Quitter")
		self.button_2 = wx.Button(self, -1, "Ouvrir")
		self.frame_1_statusbar = self.CreateStatusBar(1, 0)

		self.__set_properties()
		self.__do_layout()
		
		self.text_ctrl_1.Bind(wx.EVT_TREE_SEL_CHANGED, self.OnSel)
		self.Bind(wx.EVT_BUTTON, self.closeBrowser, self.button_1)
		self.Bind(wx.EVT_BUTTON, self.openFile, self.button_2)
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: BcliFileBrowser.__set_properties
		self.SetTitle(self.title)
		#self.text_ctrl_1.SetMinSize((380, 190))
		self.button_2.Enable(False)
		self.frame_1_statusbar.SetStatusWidths([-1])
		# statusbar fields
		frame_1_statusbar_fields = ["frame_1_statusbar"]
		for i in range(len(frame_1_statusbar_fields)):
			self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: BcliFileBrowser.__do_layout
		sizer_1 = wx.BoxSizer(wx.VERTICAL)
		sizer_2 = wx.BoxSizer(wx.VERTICAL)
		sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_2.Add(self.text_ctrl_1, 1, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 5)
		sizer_2.Add(self.static_line_1, 0, wx.ALL|wx.EXPAND, 5)
		sizer_3.Add(self.button_1, 1, wx.RIGHT|wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 5)
		sizer_3.Add(self.button_2, 1, wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 0)
		sizer_2.Add(sizer_3, 0, wx.ALL|wx.EXPAND, 5)
		sizer_1.Add(sizer_2, 1, wx.ALL|wx.EXPAND, 5)
		self.SetSizer(sizer_1)
		sizer_1.Fit(self)
		self.Layout()
		self.Centre()
		
		self.Show()
		# end wxGlade
		
	def closeBrowser(self, e):
		self.Close()
		
	def OnClose(self, e):
		self.name.Enable(True)
		e.Skip()
		
	def OnSel(self, e):
		if self.ref == 2:
			self.path = self.text_ctrl_1.GetPath()
			self.button_2.Enable(True)
		else:
			self.path = self.text_ctrl_1.GetFilePath()
			if self.path != "":
				self.button_2.Enable(True)
			else:
				self.button_2.Enable(False)
		
		self.frame_1_statusbar.SetStatusText(self.path)
		
	def openFile(self, e):
		if self.path != "":
			if self.ref == 2:
				dlg = wx.TextEntryDialog(self, 'Saisis un nom pour ce fichier', 'Nom du fichier', 'BCli')
				dlg.SetValue("")
				imagename = ""
				if dlg.ShowModal() == wx.ID_OK:
					imagename = dlg.GetValue()
				dlg.Destroy()
				if imagename != "":
					self.path = self.path + "/" + imagename
				else:
					self.path = self.path + "/rendu"
			self.field.SetValue(self.path)
			self.Close()
		else:
			dlg = wx.MessageDialog(self, 'Aucun exécutable n\'a été sélectionné...', 'Message', wx.OK | wx.ICON_ERROR)
			dlg.ShowModal()
			dlg.Destroy()	
			
