#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade HG on Sat Oct 19 13:25:43 2013

import wx

import bclifilebrowser as bfb
import sendtoblender as stb
# begin wxGlade: extracode
# end wxGlade



class Bcli(wx.Frame):
	def __init__(self, *args, **kwds):
		# begin wxGlade: Bcli.__init__
		kwds["style"] = wx.DEFAULT_FRAME_STYLE
		wx.Frame.__init__(self, *args, **kwds)
		
		binlist = []
		f = open('executables.txt', 'r')
		for l in f:
			binlist.append(str(l.strip()))
		
		self.BCli_statusbar = self.CreateStatusBar(2, 0)
		self.combo_box_1 = wx.ComboBox(self, -1, choices=binlist, style=wx.CB_DROPDOWN)
		self.combo_box_1.SetSelection(0)
		self.button_1 = wx.Button(self, -1, "Parcourir")
		self.sizer_2_staticbox = wx.StaticBox(self, -1, "Exécutable")
		self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
		self.button_2 = wx.Button(self, -1, "Parcourir")
		self.sizer_3_staticbox = wx.StaticBox(self, -1, "Fichier source")
		self.text_ctrl_1_copy = wx.TextCtrl(self, -1, "")
		self.button_2_copy = wx.Button(self, -1, "Parcourir")
		self.sizer_3_copy_staticbox = wx.StaticBox(self, -1, "Fichier destination")
		self.label_1 = wx.StaticText(self, -1, "Début")
		self.text_ctrl_2 = wx.TextCtrl(self, -1, "1")
		self.label_2 = wx.StaticText(self, -1, "Fin")
		self.text_ctrl_3 = wx.TextCtrl(self, -1, "")
		self.sizer_4_staticbox = wx.StaticBox(self, -1, "Frames")
		self.combo_box_2 = wx.ComboBox(self, -1, choices=["PNG", "JPEG", "BMP"], style=wx.CB_DROPDOWN)
		self.combo_box_2.SetSelection(0)
		self.label_3 = wx.StaticText(self, -1, "Extension")
		self.checkbox_1 = wx.CheckBox(self, -1, "")
		self.sizer_5_staticbox = wx.StaticBox(self, -1, "Format image")
		self.static_line_1 = wx.StaticLine(self, -1)
		self.button_3 = wx.Button(self, -1, "Quitter")
		self.button_4 = wx.Button(self, -1, "Réinitialiser")
		self.button_5 = wx.Button(self, -1, "Exécuter")

		self.__set_properties()
		self.__do_layout()
		
		self.Bind(wx.EVT_BUTTON, lambda evt, name=self.button_1, field=self.combo_box_1, ref=0: self.openFileBrowser(evt, name, field, ref), self.button_1)
		self.Bind(wx.EVT_BUTTON, lambda evt, name=self.button_2, field=self.text_ctrl_1, ref=1: self.openFileBrowser(evt, name, field, ref), self.button_2)
		self.Bind(wx.EVT_BUTTON, lambda evt, name=self.button_2_copy, field=self.text_ctrl_1_copy, ref=2: self.openFileBrowser(evt, name, field, ref), self.button_2_copy)
		
		self.Bind(wx.EVT_BUTTON, self.closeApp, self.button_3)
		self.Bind(wx.EVT_BUTTON, self.resetApp, self.button_4)
		self.Bind(wx.EVT_BUTTON, self.executeRender, self.button_5)
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: Bcli.__set_properties
		self.SetTitle("BCli")
		self.BCli_statusbar.SetStatusWidths([-1])
		# statusbar fields
		BCli_statusbar_fields = ["BCli_statusbar"]
		for i in range(len(BCli_statusbar_fields)):
			self.BCli_statusbar.SetStatusText(BCli_statusbar_fields[i], i)
		self.combo_box_1.SetMinSize((450, 33))
		self.combo_box_2.SetSelection(-1)
		self.checkbox_1.SetValue(1)
		
		favicon = wx.Icon('favicon.png', wx.BITMAP_TYPE_PNG, 16, 16)
		self.SetIcon(favicon)
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: Bcli.__do_layout
		sizer_main = wx.BoxSizer(wx.VERTICAL)
		sizer_1 = wx.BoxSizer(wx.VERTICAL)
		sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
		self.sizer_5_staticbox.Lower()
		sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.HORIZONTAL)
		self.sizer_4_staticbox.Lower()
		sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.HORIZONTAL)
		self.sizer_3_copy_staticbox.Lower()
		sizer_3_copy = wx.StaticBoxSizer(self.sizer_3_copy_staticbox, wx.HORIZONTAL)
		self.sizer_3_staticbox.Lower()
		sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.HORIZONTAL)
		self.sizer_2_staticbox.Lower()
		sizer_2 = wx.StaticBoxSizer(self.sizer_2_staticbox, wx.HORIZONTAL)
		sizer_2.Add(self.combo_box_1, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 5)
		sizer_2.Add(self.button_1, 0, wx.ADJUST_MINSIZE, 0)
		sizer_1.Add(sizer_2, 0, wx.ALL|wx.EXPAND, 5)
		sizer_3.Add(self.text_ctrl_1, 1, wx.RIGHT, 5)
		sizer_3.Add(self.button_2, 0, wx.ADJUST_MINSIZE, 0)
		sizer_1.Add(sizer_3, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 5)
		sizer_3_copy.Add(self.text_ctrl_1_copy, 1, wx.RIGHT|wx.ADJUST_MINSIZE, 5)
		sizer_3_copy.Add(self.button_2_copy, 0, wx.ADJUST_MINSIZE, 0)
		sizer_1.Add(sizer_3_copy, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 5)
		sizer_4.Add(self.label_1, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
		sizer_4.Add(self.text_ctrl_2, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
		sizer_4.Add(self.label_2, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
		sizer_4.Add(self.text_ctrl_3, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
		sizer_1.Add(sizer_4, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 5)
		sizer_5.Add(self.combo_box_2, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 10)
		sizer_5.Add(self.label_3, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 5)
		sizer_5.Add(self.checkbox_1, 0, wx.ADJUST_MINSIZE|wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_1.Add(sizer_5, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
		sizer_1.Add(self.static_line_1, 0, wx.ALL|wx.EXPAND, 10)
		sizer_6.Add(self.button_3, 1, wx.RIGHT|wx.ADJUST_MINSIZE, 5)
		sizer_6.Add(self.button_4, 1, wx.RIGHT|wx.ADJUST_MINSIZE, 5)
		sizer_6.Add(self.button_5, 1, wx.ADJUST_MINSIZE, 0)
		sizer_1.Add(sizer_6, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 5)
		sizer_main.Add(sizer_1, 1, wx.EXPAND, 0)
		self.SetSizer(sizer_main)
		sizer_main.Fit(self)
		self.Layout()
		self.Centre()
		# end wxGlade
		
	def openFileBrowser(self, e, name, field, ref):
		fd = bfb.BcliFileBrowser(self, name, field, ref)
		
	def closeApp(self, e):
		self.Close()
		
	def resetApp(self, e):
		#self.Close()
		print("Pas encore implémenté...")
		pass
		
	def executeRender(self, e):
		dataCollect = {"bin": self.combo_box_1.GetValue(),
						 "src": self.text_ctrl_1.GetValue(),
						 "out": self.text_ctrl_1_copy.GetValue(),
						 "start": self.text_ctrl_2.GetValue(),
						 "end": self.text_ctrl_3.GetValue(),
						 "type": self.combo_box_2.GetValue(),
						 "addext": self.checkbox_1.GetValue()}
		
		rw = stb.BCliRender(self, dataCollect)

# end of class Bcli


if __name__ == "__main__":
	app = wx.PySimpleApp(0)
	wx.InitAllImageHandlers()
	BCli = Bcli(None, -1, "")
	app.SetTopWindow(BCli)
	BCli.Show()
	app.MainLoop()
